### ISSUE TITLE
macOS Sonoma 14.7 upgrade breaks gcc header files

### ISSUE THREAD

**Issue by rod-chapman** [simonjwright/distributing-gcc#26] opened 2024-11-06 11:15 UTC
I recently upgraded to macOS Sonoma 14.7 (Apple Silicon M1).

I have GCC 14.2.0-1 from this project.

I removed and re-installed the command-line tools with `xcode-select --install`

But now, even trying to compile a trivial "hello world" program in C
```
#include <stdio.h>
int main() {
  printf("Hello\n");
  return 0;
}
```
I get
```
% gcc -c main2.c
In file included from main2.c:1:
/opt/gcc-14.2.0-1-aarch64/lib/gcc/aarch64-apple-darwin21/14.2.0/include-fixed/stdio.h:83:8: error: unknown type name ‘FILE’
   83 | extern FILE *__stdinp;
      |        ^~~~
/opt/gcc-14.2.0-1-aarch64/lib/gcc/aarch64-apple-darwin21/14.2.0/include-fixed/stdio.h:81:1: note: ‘FILE’ is defined in header ‘<stdio.h>’; this is probably fixable by adding ‘#include <stdio.h>’
   80 | #include <sys/_types/_seek_set.h>
  +++ |+#include <stdio.h>
   81 | 

```
and many more instance of the same.

I have looked in the SDK include directory, and cannot find the definition of FILE anywhere.

Any ideas?

**Comment by rod-chapman** [comment] 2024-11-06 11:33
It seems the problem is that I need it to pick up the `stdio.h` file from
```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
```
and not the one from
```
/opt/gcc-14.2.0-1-aarch64/bin/../lib/gcc/aarch64-apple-darwin21/14.2.0/include-fixed
```

**Comment by simonjwright** [comment] 2024-11-06 21:35
Issue #23 relates to this (without explanation, sorry).

The problem is that the CLT update was to version 16, which is the SDK for macOS 15, Sequoia, and GCC 14.2.0-1 was built against CLT v15, which is the SDK for macos 14, Sonoma.

The 'fixincludes' scheme is the way that GCC copes with the fact that the OS developers (Apple in this case) don’t necessarily feel obliged to make sure that their SDK is standards-compliant; and the fixed includes for CLT v15 don’t work for CLT v16. We could build against v16, but then we'd fail against v15.

* You could restore `/Library/Developer/CommandLineTools` from backup.
* You could install [GCC 14.2.0-2](https://github.com/simonjwright/distributing-gcc/releases/tag/gcc-14.2.0-2-aarch64), which finds the older SDK version squirrelled away inside CLT v16 (see below).

At a pinch you could fiddle with the contents of the SDKs: for SDK v16.1, we have
```
$ ls -l /Library/Developer/CommandLineTools/
total 0
drwxr-xr-x  5 root  wheel  160 16 Oct 06:17 Library
drwxr-xr-x  7 root  wheel  224 31 Oct 14:06 SDKs
drwxr-xr-x  7 root  wheel  224 16 Oct 06:20 usr
```
and
```
$ ls -l /Library/Developer/CommandLineTools/SDKs/
total 0
lrwxr-xr-x  1 root  wheel   14 31 Oct 14:06 MacOSX.sdk -> MacOSX15.1.sdk
drwxr-xr-x  7 root  wheel  224  8 Jul 09:09 MacOSX14.5.sdk
lrwxr-xr-x  1 root  wheel   14 31 Oct 14:05 MacOSX14.sdk -> MacOSX14.5.sdk
drwxr-xr-x  7 root  wheel  224 11 Oct 00:11 MacOSX15.1.sdk
lrwxr-xr-x  1 root  wheel   14 31 Oct 14:05 MacOSX15.sdk -> MacOSX15.1.sdk
```
so you can see it’d be possible to make that top symlink point to the `MacOSX14.5.sdk`.

But I think the other ways are better!

**Comment by rod-chapman** [comment] 2024-11-07 09:36
Many thanks Simon. I will try 14.2.0-2 and let you know how it goes.

**Comment by rod-chapman** [comment] 2024-11-07 10:22
14.2.0-2 working fine now. Many thanks.

**Closed as completed** 2024-11-07 10:22 UTC
